Telemetry correction
kubescape/taster pull request #55
Opened 2023-04-23 15:08 UTC by rcohencyberarmor

## Overview

2023-04-24 05:19 UTC, matthyx requested changes
I think we should spend some time together and I'll show you what we expect from telemetry, as it is not just error handling

2023-04-24 05:19 UTC, matthyx commented on pkg/conthandler/container_main_handler.go
> +	logger.L().Ctx(ctx).Info("stop monitor on container - after monitoring time", helpers.String("container ID", contEvent.GetContainerID()), helpers.String("container name", contEvent.GetContainerName(
we don't attach logs above Warning to spans, please remove .Ctx(ctx) from the line

2023-04-24 05:19 UTC, matthyx commented on pkg/conthandler/container_main_handler.go
> +				ctx, span := otel.Tracer("").Start(ctx, "dropped events.", trace.WithAttributes(attribute.String("containerID", contEvent.GetContainerID()), attribute.String("container workload", contEvent.GetK8
don't create a span just for the error, they should be created when you enter a part of your code that you want to trace all the time (aka. record time spent there and compare with other spans)

2023-04-25 06:29 UTC, matthyx commented
@rcohencyberarmor I corrected some things myself, PTAL

2023-04-27 08:03 UTC, rcohencyberarmor commented on pkg/conthandler/container_aggregator.go
> -			// aggregator.StopAggregate()
I removed it by purpose, the management decided to continue listen on container when we got dropped events.

2023-04-27 09:06 UTC, rcohencyberarmor commented on main.go
> +	context.SetBackgroundContext()
it must be after the config parser, so we can get account ID etc..

2023-04-28 05:15 UTC, matthyx approved these changes

2023-04-28 09:04 UTC, vladklokun approved these changes

2023-04-30 06:14 UTC, merged